name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add dotnet-sdk-9 backports
      run: sudo add-apt-repository -y ppa:dotnet/backports
    - name: Remove conflicting package
      run: sudo apt-get remove -y netstandard-targeting-pack-2.1
    - name: Install dotnet-sdk-9
      run: sudo apt-get update && sudo apt-get install -y dotnet-sdk-9.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
